apiVersion: v1
kind: Pod
metadata:
  name: labels
  namespace: roboshop
  labels:
    environment: development
    app: nginx
spec: 
  containers:
  - name: nginx-labels
    image: nginx
    ports:
    - containerPort: 80
